---
name: kube

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy to server
    runs-on: ubuntu-latest
    steps:
      - uses: danielr1996/kubectl-action@1.0.0
        name: Deploy
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: apply -f k8s